// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
<<<<<<< HEAD
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
=======
  | 'item-section-chat-fullHeight'
  | 'item-section-chat-head-text'
  | 'item-section-chat-sidenav-tooltip'
>>>>>>> feature/chat-pane
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'pref-api-key'
  | 'pref-llm-option-goethe'
  | 'pref-llm-option-local'
  | 'pref-llm-option-openai'
  | 'pref-llm-provider'
  | 'pref-model'
  | 'pref-port'
  | 'pref-prompt'
  | 'pref-temp'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
