// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llmProvider": string;
      "localPort": string;
      "openaiApiKey": string;
      "openaiModel": string;
      "openaiTemp": string;
      "openaiPrompt": string;
      "goetheApiKey": string;
      "goetheModel": string;
      "goetheTemp": string;
      "goethePrompt": string;
    };
  }
}
